name: "Build and push docker container"

on:
  pull_request:
  workflow_dispatch:

env:
  GOPRIVATE: github.com/weaveworks/cluster-controller

jobs:
  cluster-bootstrap-controller:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19.x
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Configure git for private modules
      env:
        GITHUB_BUILD_USERNAME: ${{ secrets.BUILD_BOT_USER }}
        GITHUB_BUILD_TOKEN: ${{ secrets.BUILD_BOT_PERSONAL_ACCESS_TOKEN }}
      run: git config --global url."https://${GITHUB_BUILD_USERNAME}:${GITHUB_BUILD_TOKEN}@github.com".insteadOf "https://github.com"
    - name: Build | Test
      run: |
        go version
        make test
    - name: Publish | Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build docker image
      env:
        GITHUB_BUILD_USERNAME: ${{ secrets.BUILD_BOT_USER }}
        GITHUB_BUILD_TOKEN: ${{ secrets.BUILD_BOT_PERSONAL_ACCESS_TOKEN }}
      run: |
        make docker-build
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.WGE_DOCKER_IO_USER }}
        password: ${{ secrets.WGE_DOCKER_IO_PASSWORD }}
    - name: Push image to docker registry
      run: |
        make docker-push


